version: '3'

services:

  ca.kisa.bclec.co.kr:
      restart: always
      container_name: ca.kisa.bclec.co.kr
      image: hyperledger/fabric-ca:1.4.0
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.kisa.bclec.co.kr
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.kisa.bclec.co.kr-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/aa5c652ec676b848f9db6622ce06fb487239d5c55e3c6c2d67ec61c1eccb3ec4_sk
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
        - ./crypto-config/peerOrganizations/kisa.bclec.co.kr/ca:/etc/hyperledger/fabric-ca-server-config
      ports:
        - 7054:7054

  ca.smartm2m.bclec.co.kr:
      restart: always
      container_name: ca.smartm2m.bclec.co.kr
      image: hyperledger/fabric-ca:1.4.0
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.smartm2m.bclec.co.kr
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.smartm2m.bclec.co.kr-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5449a086c10a4bdf0132b8487c4ee2c3709c6f706d8bd2c02c3bd791decc972b_sk
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
        - ./crypto-config/peerOrganizations/smartm2m.bclec.co.kr/ca:/etc/hyperledger/fabric-ca-server-config
      ports:
        - 8054:7054

  orderer0.bclec.co.kr:
    container_name: orderer0.bclec.co.kr
    image: hyperledger/fabric-orderer:1.4.0
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_LOCALMSPDIR=crypto-config/ordererOrganizations/bclec.co.kr/orderers/orderer0.bclec.co.kr/msp
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
    depends_on:

      - kafka0.bclec.co.kr
    ports:
      - 7050:7050

  kafka0.bclec.co.kr:
    container_name: kafka0.bclec.co.kr
    image: hyperledger/fabric-kafka:0.4.14
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zk.bclec.co.kr:2181
    depends_on:
      - zk.bclec.co.kr

  zk.bclec.co.kr:
    restart: always
    container_name: zk.bclec.co.kr
    image: hyperledger/fabric-zookeeper:0.4.14

  couchdb.peer0.kisa.bclec.co.kr:
    container_name: couchdb.peer0.kisa.bclec.co.kr
    image: hyperledger/fabric-couchdb:0.4.14
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 5984:5984

  peer0.kisa.bclec.co.kr:
    container_name: peer0.kisa.bclec.co.kr
    image: hyperledger/fabric-peer:1.4.0
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_MSPCONFIGPATH=crypto-config/peerOrganizations/kisa.bclec.co.kr/peers/peer0.kisa.bclec.co.kr/msp
      - CORE_PEER_LOCALMSPID=kisaOrg
      - CORE_PEER_ID=peer0.kisa.bclec.co.kr
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.kisa.bclec.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.kisa.bclec.co.kr:7051
    working_dir: /etc/hyperledger/fabric
    links:
      - couchdb.peer0.kisa.bclec.co.kr:couchdb
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  couchdb.peer0.smartm2m.bclec.co.kr:
    container_name: couchdb.peer0.smartm2m.bclec.co.kr
    image: hyperledger/fabric-couchdb:0.4.14
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 6984:5984

  peer0.smartm2m.bclec.co.kr:
    container_name: peer0.smartm2m.bclec.co.kr
    image: hyperledger/fabric-peer:1.4.0
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_MSPCONFIGPATH=crypto-config/peerOrganizations/smartm2m.bclec.co.kr/peers/peer0.smartm2m.bclec.co.kr/msp
      - CORE_PEER_LOCALMSPID=smartm2mOrg
      - CORE_PEER_ID=peer0.smartm2m.bclec.co.kr
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.smartm2m.bclec.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.smartm2m.bclec.co.kr:7051
    working_dir: /etc/hyperledger/fabric
    links:
      - couchdb.peer0.smartm2m.bclec.co.kr:couchdb
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.0
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_MSPCONFIGPATH=crypto-config/peerOrganizations/kisa.bclec.co.kr/peers/peer0.kisa.bclec.co.kr/msp
      - CORE_PEER_LOCALMSPID=kisaOrg
      - CORE_PEER_ID=cli.peer0.kisa.bclec.co.kr
      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb
    working_dir: /etc/hyperledger/fabric
    command: sh -c "peer node start"
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
      - $GOPATH:/opt/gopath
